apiVersion: apps/v1
kind: Deployment
metadata:
  name: udagram-users-api
  labels:
    app: udagram-users-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram-users-api
  template:
    metadata:
      labels:
        app: udagram-users-api
    spec:
      containers:
      - name: udagram-users-api
        image: mcharaf/udagram-users-api
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: users-settings