apiVersion: v1
kind: Service
metadata:
  name: udagram-users-api
  labels:
    run: udagram-users-api
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    run: udagram-users-api