apiVersion: v1
kind: Service
metadata:
  name: udagram-feed-api
  labels:
    run: udagram-feed-api
spec:
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    run: udagram-feed-api